# Generated by Django 3.2.14 on 2022-08-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20220726_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='expired',
        ),
    ]
