# Generated by Django 3.2.14 on 2022-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_remove_profile_token_for_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
    ]
